<template>
  <div id="SlidesContainer" class="page-slides slides scroll smooth smoothScroll animated noPreload">
    <SvgLibrary></SvgLibrary>
    <Panels :toggleSignup="toggleSignup"></Panels>

    <section class="slide slide1 whiteSlide">
      <div class="content">
        <div class="container">
          <div class="wrap padding-bottom-2">
            <div class="fix-12-12 policy-page">
              <h1 class="page-title">Privacy Policy</h1>
              <div class="page-subtitle">
                <p>Last Updated: Dec 27, 2022</p>
                <p>Effective Date: Dec 27, 2022</p>
              </div>
              <div class="policy-content">
                <div class="p">
                  <div class="p-title">1. Introduction</div>
                  <div class="p-content">
                    <p>Welcome to Datalego Inc.</p>
                    <p>Datalego Inc. (“us”, “we”, “Datalego”, or “our”) operates <a href="https://www.zettablock.com/" target="_blank">https://www.zettablock.com/</a> or relevant subdomains (<a href="https://app.zettablock.com/" target="_blank">https://app.zettablock.com/</a>, <a href="https://demo.zettablock.dev/" target="_blank">https://demo.zettablock.dev/</a>) (together or individually the “Service”).</p>
                    <p>This Privacy Policy assists you as the User (defined below) of our Service to understand which information we collect, why we collect information, how we use information and the data privacy rights you have as the User.</p>
                    <p>We use your data to provide and improve our Service. Before using our Service, please review this Privacy Policy carefully and contact us if you have any questions. By using our Service, you agree to the collection and use of information in accordance with this policy.</p>
                  </div>
                </div>
                <div class="p">
                  <div class="p-title">2. Definitions</div>
                  <dvi class="p-content">
                    <p><span class="bold">SERVICE</span> means https://www.zettablock.com/ or relevant subdomains (https://app.zettablock.com/, https://demo.zettablock.dev/) operated by Datalego.</p>
                    <p><span class="bold">PERSONAL DATA</span> means data about an individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                    <p><span class="bold">USAGE DATA</span> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
                    <p><span class="bold">COOKIES</span> are small files stored on your device (computer or mobile device).</p>
                    <p><span class="bold">DATA SUBJECT</span> is any individual who is the subject of Personal Data.</p>
                    <p><span class="bold">THE USER</span> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
                  </dvi>
                </div>
                <div class="p">
                  <div class="p-title">3. Information We Collect</div>
                  <div class="p-content">
                    <p>Datalego collects different types of information for the purposes of providing and improving our Service to you.</p>
                  </div>
                  <div class="p-subtitle">3.1. Personal Data</div>
                  <div class="p-content">
                    <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:</p>
                    <div class="order-content">
                      <p data-order="A.">First name and last name</p>
                      <p data-order="B.">Email address</p>
                      <p data-order="C.">Username</p>
                      <p data-order="D.">IP address</p>
                      <p data-order="E.">Web browser</p>
                      <p data-order="F.">Phone number</p>
                      <p data-order="G.">Address, State, Province, ZIP/Postal code, City</p>
                      <p data-order="H.">Cookies and Usage Data</p>
                    </div>
                    <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p>
                  </div>
                  <div class="p-subtitle">3.2. Usage Data</div>
                  <div class="p-content">
                    <p>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (“Usage Data”).</p>
                    <p>This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                    <p>When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>
                  </div>
                  <div class="p-subtitle">3.3. Cookies</div>
                  <div class="p-content">
                    <p>We use Cookies on our website and products that are strictly necessary for our Service to function.</p>
                    <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track.</p>
                    <p>These Cookies are always active, as they are necessary for our website and our products to function. If you wish to turn off these cookies, you can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, please note our Service will not function properly. We do not share information gathered using cookies with any third parties.</p>
                    <p>Examples of Cookies we use:</p>
                    <div class="order-content">
                      <p data-order="1.">Session Cookies: We use Session Cookies to operate our Service.</p>
                      <p data-order="2.">Preference Cookies: We use Preference Cookies to remember your preferences and various settings.</p>
                      <p data-order="3.">Security Cookies: We use Security Cookies for security purposes.</p>
                      <p data-order="4.">Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</p>
                    </div>
                  </div>
                </div>
                <div class="p">
                  <div class="p-title">4. Use of Information</div>
                  <div class="p-content">
                    <p>Any processing of personal data by Datalego is conducted in accordance with applicable data privacy legislation.We may use the collected data for the following purposes:</p>
                    <div class="order-content">
                      <p data-order="1.">To administrate access and provide you with the Service;</p>
                      <p data-order="2.">To maintain our Service;</p>
                      <p data-order="3.">To send administrative information to you, for example, information regarding updates to our Service or changes to this Privacy Policy or other agreements relevant to your use of our Service.</p>
                      <p data-order="4.">To detect, prevent and address technical issues;</p>
                      <p data-order="5.">To provide customer support;</p>
                      <p data-order="6.">To gather analysis or valuable information so that we can improve our Service;</p>
                      <p data-order="7.">To monitor the usage of our Service;</p>
                      <p data-order="8.">To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</p>
                      <p data-order="9.">To provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</p>
                      <p data-order="10.">To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information; in any other way we may describe when you provide the information;</p>
                      <p data-order="11.">For other purposes that we have explicitly received your consent.</p>
                    </div>
                  </div>
                </div>
                <div class="p">
                  <div class="p-title">5. Retention Period</div>
                  <div class="p-content">
                    <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                    <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
                    <p>We will delete all data upon request or termination of your user account.</p>
                  </div>
                </div>
                <div class="p">
                  <div class="p-title">6. Who We Share Your Information With</div>
                  <div class="p-content">
                    <p>Datalego will not share the Personal Data of its users with any third parties, except when we have legal grounds for sharing the data or it is required under any statutory obligations Datalego is subject to.</p>
                    <p>We share your data only with our processors, with the sole purpose of providing the service to you.</p>
                    <div class="order-content">
                      <p data-order="1.">We may provide paid products and/or services within Service. In that case, we use third party services for payment processing (e.g. payment processors).</p>
                      <p data-order="" class="mt-10">We use Stripe as our processor for conducting payments. We will not store or collect your payment card details. Stripe is located in the US. We only send your email through Stripe, and we have entered into EU standard contractual to ensure the use of Stripe is in accordance with relevant privacy legislation.</p>
                      <p data-order="" class="mt-10">Their Privacy Policy can be viewed at: <a href="https://stripe.com/us/privacy" target="_blank">https://stripe.com/us/privacy</a> .</p>
                    </div>
                  </div>
                </div>
                <div class="p">
                  <div class="p-title">7. Your Rights</div>
                  <div class="p-content">
                    <p>When providing us with your Personal Data, you may request access to your Personal Data, as well as information on how we process your Personal Data. You may also request rectification, erasure and restriction of the processing, as well as to have your Personal Data exported in a structured, commonly used and machine-readable format (data portability).</p>
                    <p>Requests pursuant to the above rights may submitted to: <a href="mailto:team@zettablock.com">team@zettablock.com</a></p>
                    <p>You may also file a complaint to your applicable data protection authority if you are of the opinion that Datalego has failed to comply with your rights as a data subject.</p>
                  </div>
                </div>
                <div class="p">
                  <div class="p-title">8. Changes to This Privacy Policy</div>
                  <div class="p-content">
                    <p>We may revise our Privacy Policy from time to time at our sole discretion. If there are any material changes to this Privacy Policy, we will notify you and obtain your consent before you are permitted to continue to use the site as required by applicable law.</p>
                    <p>You understand and agree that you will be deemed to have accepted the updated Privacy Policy if you continue to use our services after the new Privacy Policy takes effect. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                  </div>
                </div>
                <div class="p">
                  <div class="p-title">9. Contact Us</div>
                  <div class="p-content">
                    <p>If you have any questions about this Privacy Policy, please contact us by email: <a href="mailto:team@zettablock.com">team@zettablock.com</a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="background" style="background: url(/assets/images/slide1_bg.png) no-repeat top center / 100%"></div>
    </section>

    <page-footer></page-footer>

    <SignupDialog v-model="signupDialogVisible"></SignupDialog>
  </div>

</template>

<script>
  import { slidesFunction } from "../utils/slides_v5.2.1";
  import SvgLibrary from "../components/SvgLibrary.vue";
  import Panels from "../components/Panels.vue";
  import SectionCode from "../components/SectionCode.vue";
  import SignupDialog from "../components/SignupDialog.vue";
  import PageFooter from "../components/PageFooter.vue";
  import bounty from "../utils/bounty";
  import Swiper, {Pagination} from 'swiper'
  import gsap from 'gsap'
  import ScrollTrigger from 'gsap/ScrollTrigger'
  gsap.registerPlugin(ScrollTrigger)

  export default {
    name: "home",
    components: {
      SvgLibrary,
      Panels,
      SectionCode,
      SignupDialog,
      PageFooter,
    },
    data() {
      return {
        scrollOffer: 0,
        signupDialogVisible: false,
      };
    },
    created() {
      document.title = "ZettaBlock - The First Full-stack, Real-time Web3 Data Infra";
    },
    mounted() {
      setTimeout(() => {
        this.onCreateView();
      }, 100);
    },
    watch: {},
    destroyed() {
      this.removeHome();
    },
    methods: {
      toggleSignup() {
        this.signupDialogVisible = true
      },
      onCreateView() {
        document.querySelector("body").classList.add("posr");
        slidesFunction();
        window.scrollTo(0, 1);
      },
      removeHome() {
        $("body").removeClass("posr");
        $(window).off("mousemove");
      },
      clicklSrcoll(t) {
        if (t == "left") {
          this.scrollOffer += 960;
        } else if (t == "right") {
          this.scrollOffer -= 960;
        }
        const elem = document.getElementById("marquee");
        if (this.scrollOffer < 0) {
          this.scrollOffer = 0;
        }
        if (this.scrollOffer >= elem.scrollWidth) {
          this.scrollOffer = elem.scrollWidth;
        }
        elem.scrollTo(this.scrollOffer, 0);
      },
    },
  };
</script>

<style lang="scss">
@import '../scss/home.scss';
@import '../scss/home.mobile.scss';
</style>
